import srcimg from '$lib/images/UpCard_Logo.png';

export default {
    img: {
        src: srcimg,
        alt: 'UPCARD Thumbnail'
    },
    href: 'https://bnuey.itch.io/UPCARD',
    title: 'UPCARD',
    date: '8/1/2025',
    info: "My first full game.<br>Developed over the summer of '24 and '25",
    description: "UPCARD is a tabletop card game that puts in a spin on the typical BlackJack game played across casinos. Use items, deduction, and skill to beat the host at his own game.",
    anecdote: "UPCARD is my baby, I love this game with all my heart. I had the idea for this game back in early 2024 and felt like it was small enough scope to finish over the summer. How wrong I was, even with cutting out a lot of the other features I had planned it still took 2 summers of hard work to finish it. Even games that seem small are probably 2-3 times as big as you can reasonably do. . . Since this was one of my first projects, created soon after QuestionHeir, the project was a disaster as I was still trying to figure out a nice workflow. Coming back to it the next summer was painful because nothing made any sense and the codebase was a disaster. I wanted to finish this game so bad though, I really enjoyed playing the game and thought the mechanics were interesting. I had spent so much time on it already it felt wrong not to finish it. So I got everything together, reorganized the project, and found some tools that helped tremendiously. I don't think I would have finished the game without Quantum Console, the single best Unity asset I have ever used. I came up with so many clever solutions for the problems I was having. Controller support for example is completely faked. When I started I hadn't thought ahead to how I was going to add controller support, and contimplated not doing it at all, but I came up with a solution. Get all the current interactable objects -> Put them in a list -> and then bind left and right to scroll through that list, and A simulates a click on them. There was more technical details to work out but that is basically how it works. It's so simple too. It felt so good coming back to the project with new knowledge I didn't have before and being able to make quick work of a task that would have taken me all day before. UPCARD Got progressively sillier and sillier as time went on, and I'm glad I doubled down on the absurdity. This game is incredibly special to me, as my first real full game. A game on my itch page that wasn't made in a week or two. But with all due respect, I'm glad this game is out of my life. The feeling of finishing a game is unmatched, the endless grind of opening the game, playtesting, coding, animating... it's over... It hit me a couple days after I released it, I fucking finished a game and I'm so proud of myself. I do of course have to thank my two great friends Jayden Wisnuiski and Chase Seams, actually did me the biggest favours in the world by creating all the promotional art, and almost all the music respectively. The game wouldn't be the same without them and their work, and I think them both for being there when I needed a helping hand the most Ɛ>"
}
